version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 53306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 56379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
